spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Bot?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
server:
  port: 8080

facebook:
  messenger:
  access-token: EAAPmX9sA2m8BAADxQiD1UOwqVONMeZBZAqB7zZBwoeqfrSTjkXr25qY3kzx3Est61uwsBAu57n764qPDGwG6IdbgeYvbvTvG9HtIgvfGjjZBsmNhd6aJp3N6JjRiKFJXtWEqty2qmkfEmZARYJrMn1Gk52hxgeShTVJV7fG4BJgZDZD


